markdown: redcarpet
name: Solidus Guides
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: Ash Kamel
  url: https://solidus.io

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/solidus-logo.png
logoalt: Solidus Logo

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
- text: Users
  url: users/
  internal: true
  children:
  - text: Overview
    url: overview/
    internal: true
  - text: Configuration
    url: configuration/
    internal: true
    expand_nav: false
    children:
    - text: Configuring Analytics
      url: configuring_analytics/
      internal: true
    - text: Configuring Settings
      url: configuring_general_settings/
      internal: true
    - text: Configuring Geography
      url: configuring_geography/
      internal: true
    - text: Configuring Inventory
      url: configuring_inventory/
      internal: true
    - text: Configuring Mail Methods
      url: configuring_mail_ethods/
      internal: true
    - text: Configuring Shipping
      url: configuring_shipping/
      internal: true
    - text: Configuring Taxes
      url: configuring_taxes/
      internal: true
    - text: Configuring Taxonomies
      url: configuring_taxonomies/
      internal: true
  - text: Orders
    url: orders/
    internal: true
    expand_nav: false
    children:
    - text: Editing Orders
      url: editing_orders/
      internal: true
    - text: Entering Orders
      url: enter_orders/
      internal: true
    - text: Order States
      url: order_states/
      internal: true
    - text: Processing Orders
      url: processing_orders/
      internal: true
    - text: Returning Orders
      url: returning_orders/
      internal: true
    - text: Searching Orders
      url: searching_orders/
      internal: true
  - text: Payments
    url: payments/
    expand_nav: false
    internal: true
    children:
    - text: Payment methods
      url: payment_methods/
      internal: true
    - text: Payment States
      url: payment_states/
      internal: true
  - text: Products
    url: products/
    expand_nav: false
    internal: true
    children:
    - text: Cloning Products
      url: cloning_products/
      internal: true
    - text: Creating Products
      url: creating_products/
      internal: true
    - text: Deleting Products
      url: deleting_products/
      internal: true
    - text: Editing Products
      url: editing_products/
      internal: true
    - text: Product Options
      url: product_options/
      internal: true
    - text: Product Properties
      url: product_properties/
      internal: true
    - text: product_prototypes
      url: product_prototypes/
      internal: true
    - text: Searching Products
      url: searching_products/
      internal: true
  - text: Shipments
    url: shipments/
    expand_nav: false
    internal: true
    children:
    - text: Calculations
      url: calculations/
      internal: true
    - text: Shipping Categories
      url: shipping_categories/
      internal: true
    - text: Shipping Methods
      url: shipping_methods/
      internal: true
    - text: Zones
      url: zones/
      internal: true
  - text: Extensions
    url: extensions/
    internal: true
  - text: Promotions
    url: promotions/
    internal: true
  - text: Reports
    url: reports/
    internal: true

repos:
- name: Guides Template
  description: Main repository
  url: https://github.com/ajkamel/solidus-guides

back_link:
  url: "https://ajkamel.github.io/solidus-guides/"
  text: Read more Solidus Guides

google_analytics_ua:

collections:
  pages:
    output: true
    permalink: /:path/

baseurl: '/solidus-guides'

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
